### ISSUE TITLE
[Bug] Double Slash in Validation Error

### ISSUE THREAD

**Issue by kbiits** [laravel-json-api/validation#4]
Found double Slash when using withSourcePrefix method in ValidationErrorIterator class

```
public function withSourcePrefix(string $prefix): self
    {
        $prefix = rtrim($prefix, '/');
        $this->withPointers(
            fn($key) => sprintf('%s%s', $prefix, $this->convertKey($key))
        );
        return $this;
    }
```

Validation Error Response result

```
{
    "jsonapi": {
        "version": "1.0"
    },
    "errors": [
        {
            "detail": "Field nama tidak boleh kosong",
            "source": {
                "pointer": "data/attributes//name"
            },
            "status": "422",
            "title": "Unprocessable Entity"
        }
    ]
}
```

**Comment by kbiits** [comment]
#5

**Comment by lindyhopchris** [comment]
Looking at that, it should also have a `/` at the start, i.e. it should be `/data/attributes/name`.

I think therefore we should change `rtrim` to `trim` so it is trimmed at the start and the end. Then change the sprintf to `"/%s%s"` - so that we always ensure the developer gets a starting `/`.

Could you amend your PR?

This also shows I need to add some unit tests for this class as clearly it's not tested at the moment (I don't think I've used it in any of the applications I have, which is why I haven't picked up on these bugs before).
